name: solar system workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main 
      - feature/*

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.Mongo_PASSWORD }}

jobs:
  unit-testing:
    name: unit testing
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
        nodejs_version: [18, 19, 20]
        exclude:
          - nodejs_version: 18
            operating-system: macos-latest
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        
      - name: setup Nodejs version
        uses: actions/setup-node@v4 -  ${{ matrix.nodejs_version }}
        with:
          node-version: ${{matrix.nodejs_version}}

      - name: install dependencies
        run: npm install
      
      - name: unit testing
        run: npm test
      
      - name: mocha test result
        uses: actions/upload-artifact@v4
        with:
          name: test result
          path: test-results.xml
          