name: solar system workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main 
      - feature/*

jobs:
  unit-testing:
    name: unit testing
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: ./.github/actions/checkout@v4
        
      - name: setup Nodejs version
        uses: ./.github/actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        uses: npm install
      
      - name: unit testing
        run: npm test
          